// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

// Protobuf Java Version: 3.25.1
package com.lee9213.proto;

public final class PersonClassName {
  private PersonClassName() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lee9213_protobuf_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lee9213_protobuf_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lee9213_protobuf_StudentPerson_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lee9213_protobuf_StudentPerson_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lee9213_protobuf_TeacherPerson_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lee9213_protobuf_TeacherPerson_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Person.proto\022\024com.lee9213.protobuf\"\202\002\n" +
      "\006Person\022@\n\npersonEnum\030\001 \001(\0162\'.com.lee921" +
      "3.protobuf.Person.PersonEnumH\001\210\001\001\0222\n\003stu" +
      "\030\002 \001(\0132#.com.lee9213.protobuf.StudentPer" +
      "sonH\000\0221\n\002te\030\003 \001(\0132#.com.lee9213.protobuf" +
      ".TeacherPersonH\000\"2\n\nPersonEnum\022\021\n\rStuden" +
      "tPerson\020\000\022\021\n\rTeacherPerson\020\001B\014\n\nPersonTy" +
      "peB\r\n\013_personEnum\"g\n\rStudentPerson\022\021\n\004na" +
      "me\030\001 \001(\tH\000\210\001\001\022\020\n\003age\030\002 \001(\005H\001\210\001\001\022\024\n\007addre" +
      "ss\030\003 \001(\tH\002\210\001\001B\007\n\005_nameB\006\n\004_ageB\n\n\010_addre" +
      "ss\"g\n\rTeacherPerson\022\021\n\004name\030\001 \001(\tH\000\210\001\001\022\020" +
      "\n\003age\030\002 \001(\005H\001\210\001\001\022\024\n\007address\030\003 \001(\tH\002\210\001\001B\007" +
      "\n\005_nameB\006\n\004_ageB\n\n\010_address2i\n\rPersonSer" +
      "vice\022X\n\ngetStudent\022#.com.lee9213.protobu" +
      "f.TeacherPerson\032#.com.lee9213.protobuf.S" +
      "tudentPerson\"\000B)\n\024com.lee9213.protobufB\017" +
      "PersonClassNameP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_lee9213_protobuf_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lee9213_protobuf_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lee9213_protobuf_Person_descriptor,
        new java.lang.String[] { "PersonEnum", "Stu", "Te", "PersonType", });
    internal_static_com_lee9213_protobuf_StudentPerson_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_lee9213_protobuf_StudentPerson_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lee9213_protobuf_StudentPerson_descriptor,
        new java.lang.String[] { "Name", "Age", "Address", });
    internal_static_com_lee9213_protobuf_TeacherPerson_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_lee9213_protobuf_TeacherPerson_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lee9213_protobuf_TeacherPerson_descriptor,
        new java.lang.String[] { "Name", "Age", "Address", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
