//// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// source: src/protobuf/Student.proto
//// Protobuf Java Version: 4.26.0
//
//package com.lee9213.protobuf;
//
//public final class StudentClassName {
//  private StudentClassName() {}
//  static {
//    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
//      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
//      /* major= */ 4,
//      /* minor= */ 26,
//      /* patch= */ 0,
//      /* suffix= */ "",
//      StudentClassName.class.getName());
//  }
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistryLite registry) {
//  }
//
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistry registry) {
//    registerAllExtensions(
//        (com.google.protobuf.ExtensionRegistryLite) registry);
//  }
//  public interface StudentPersonOrBuilder extends
//      // @@protoc_insertion_point(interface_extends:com.lee9213.proto.StudentPerson)
//      com.google.protobuf.MessageOrBuilder {
//
//    /**
//     * <code>optional string name = 1;</code>
//     * @return Whether the name field is set.
//     */
//    boolean hasName();
//    /**
//     * <code>optional string name = 1;</code>
//     * @return The name.
//     */
//    java.lang.String getName();
//    /**
//     * <code>optional string name = 1;</code>
//     * @return The bytes for name.
//     */
//    com.google.protobuf.ByteString
//        getNameBytes();
//
//    /**
//     * <code>optional int32 age = 2;</code>
//     * @return Whether the age field is set.
//     */
//    boolean hasAge();
//    /**
//     * <code>optional int32 age = 2;</code>
//     * @return The age.
//     */
//    int getAge();
//
//    /**
//     * <code>optional string address = 3 [default = "&#92;346&#92;261&#92;237&#92;350&#92;213&#92;217"];</code>
//     * @return Whether the address field is set.
//     */
//    boolean hasAddress();
//    /**
//     * <code>optional string address = 3 [default = "&#92;346&#92;261&#92;237&#92;350&#92;213&#92;217"];</code>
//     * @return The address.
//     */
//    java.lang.String getAddress();
//    /**
//     * <code>optional string address = 3 [default = "&#92;346&#92;261&#92;237&#92;350&#92;213&#92;217"];</code>
//     * @return The bytes for address.
//     */
//    com.google.protobuf.ByteString
//        getAddressBytes();
//  }
//  /**
//   * Protobuf type {@code com.lee9213.proto.StudentPerson}
//   */
//  public static final class StudentPerson extends
//      com.google.protobuf.GeneratedMessage implements
//      // @@protoc_insertion_point(message_implements:com.lee9213.proto.StudentPerson)
//      StudentPersonOrBuilder {
//  private static final long serialVersionUID = 0L;
//    static {
//      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
//        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
//        /* major= */ 4,
//        /* minor= */ 26,
//        /* patch= */ 0,
//        /* suffix= */ "",
//        StudentPerson.class.getName());
//    }
//    // Use StudentPerson.newBuilder() to construct.
//    private StudentPerson(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
//      super(builder);
//    }
//    private StudentPerson() {
//      name_ = "";
//      address_ = com.google.protobuf.Internal.stringDefaultValue("\346\261\237\350\213\217");
//    }
//
//    public static final com.google.protobuf.Descriptors.Descriptor
//        getDescriptor() {
//      return com.lee9213.protobuf.StudentClassName.internal_static_com_lee9213_protobuf_StudentPerson_descriptor;
//    }
//
//    @java.lang.Override
//    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
//        internalGetFieldAccessorTable() {
//      return com.lee9213.protobuf.StudentClassName.internal_static_com_lee9213_protobuf_StudentPerson_fieldAccessorTable
//          .ensureFieldAccessorsInitialized(
//              com.lee9213.protobuf.StudentClassName.StudentPerson.class, com.lee9213.protobuf.StudentClassName.StudentPerson.Builder.class);
//    }
//
//    private int bitField0_;
//    public static final int NAME_FIELD_NUMBER = 1;
//    @SuppressWarnings("serial")
//    private volatile java.lang.Object name_ = "";
//    /**
//     * <code>optional string name = 1;</code>
//     * @return Whether the name field is set.
//     */
//    @java.lang.Override
//    public boolean hasName() {
//      return ((bitField0_ & 0x00000001) != 0);
//    }
//    /**
//     * <code>optional string name = 1;</code>
//     * @return The name.
//     */
//    @java.lang.Override
//    public java.lang.String getName() {
//      java.lang.Object ref = name_;
//      if (ref instanceof java.lang.String) {
//        return (java.lang.String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        java.lang.String s = bs.toStringUtf8();
//        if (bs.isValidUtf8()) {
//          name_ = s;
//        }
//        return s;
//      }
//    }
//    /**
//     * <code>optional string name = 1;</code>
//     * @return The bytes for name.
//     */
//    @java.lang.Override
//    public com.google.protobuf.ByteString
//        getNameBytes() {
//      java.lang.Object ref = name_;
//      if (ref instanceof java.lang.String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (java.lang.String) ref);
//        name_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    public static final int AGE_FIELD_NUMBER = 2;
//    private int age_ = 0;
//    /**
//     * <code>optional int32 age = 2;</code>
//     * @return Whether the age field is set.
//     */
//    @java.lang.Override
//    public boolean hasAge() {
//      return ((bitField0_ & 0x00000002) != 0);
//    }
//    /**
//     * <code>optional int32 age = 2;</code>
//     * @return The age.
//     */
//    @java.lang.Override
//    public int getAge() {
//      return age_;
//    }
//
//    public static final int ADDRESS_FIELD_NUMBER = 3;
//    @SuppressWarnings("serial")
//    private volatile java.lang.Object address_ = com.google.protobuf.Internal.stringDefaultValue("\346\261\237\350\213\217");
//    /**
//     * <code>optional string address = 3 [default = "&#92;346&#92;261&#92;237&#92;350&#92;213&#92;217"];</code>
//     * @return Whether the address field is set.
//     */
//    @java.lang.Override
//    public boolean hasAddress() {
//      return ((bitField0_ & 0x00000004) != 0);
//    }
//    /**
//     * <code>optional string address = 3 [default = "&#92;346&#92;261&#92;237&#92;350&#92;213&#92;217"];</code>
//     * @return The address.
//     */
//    @java.lang.Override
//    public java.lang.String getAddress() {
//      java.lang.Object ref = address_;
//      if (ref instanceof java.lang.String) {
//        return (java.lang.String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        java.lang.String s = bs.toStringUtf8();
//        if (bs.isValidUtf8()) {
//          address_ = s;
//        }
//        return s;
//      }
//    }
//    /**
//     * <code>optional string address = 3 [default = "&#92;346&#92;261&#92;237&#92;350&#92;213&#92;217"];</code>
//     * @return The bytes for address.
//     */
//    @java.lang.Override
//    public com.google.protobuf.ByteString
//        getAddressBytes() {
//      java.lang.Object ref = address_;
//      if (ref instanceof java.lang.String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (java.lang.String) ref);
//        address_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    private byte memoizedIsInitialized = -1;
//    @java.lang.Override
//    public final boolean isInitialized() {
//      byte isInitialized = memoizedIsInitialized;
//      if (isInitialized == 1) return true;
//      if (isInitialized == 0) return false;
//
//      memoizedIsInitialized = 1;
//      return true;
//    }
//
//    @java.lang.Override
//    public void writeTo(com.google.protobuf.CodedOutputStream output)
//                        throws java.io.IOException {
//      if (((bitField0_ & 0x00000001) != 0)) {
//        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
//      }
//      if (((bitField0_ & 0x00000002) != 0)) {
//        output.writeInt32(2, age_);
//      }
//      if (((bitField0_ & 0x00000004) != 0)) {
//        com.google.protobuf.GeneratedMessage.writeString(output, 3, address_);
//      }
//      getUnknownFields().writeTo(output);
//    }
//
//    @java.lang.Override
//    public int getSerializedSize() {
//      int size = memoizedSize;
//      if (size != -1) return size;
//
//      size = 0;
//      if (((bitField0_ & 0x00000001) != 0)) {
//        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
//      }
//      if (((bitField0_ & 0x00000002) != 0)) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeInt32Size(2, age_);
//      }
//      if (((bitField0_ & 0x00000004) != 0)) {
//        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, address_);
//      }
//      size += getUnknownFields().getSerializedSize();
//      memoizedSize = size;
//      return size;
//    }
//
//    @java.lang.Override
//    public boolean equals(final java.lang.Object obj) {
//      if (obj == this) {
//       return true;
//      }
//      if (!(obj instanceof com.lee9213.protobuf.StudentClassName.StudentPerson)) {
//        return super.equals(obj);
//      }
//      com.lee9213.protobuf.StudentClassName.StudentPerson other = (com.lee9213.protobuf.StudentClassName.StudentPerson) obj;
//
//      if (hasName() != other.hasName()) return false;
//      if (hasName()) {
//        if (!getName()
//            .equals(other.getName())) return false;
//      }
//      if (hasAge() != other.hasAge()) return false;
//      if (hasAge()) {
//        if (getAge()
//            != other.getAge()) return false;
//      }
//      if (hasAddress() != other.hasAddress()) return false;
//      if (hasAddress()) {
//        if (!getAddress()
//            .equals(other.getAddress())) return false;
//      }
//      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
//      return true;
//    }
//
//    @java.lang.Override
//    public int hashCode() {
//      if (memoizedHashCode != 0) {
//        return memoizedHashCode;
//      }
//      int hash = 41;
//      hash = (19 * hash) + getDescriptor().hashCode();
//      if (hasName()) {
//        hash = (37 * hash) + NAME_FIELD_NUMBER;
//        hash = (53 * hash) + getName().hashCode();
//      }
//      if (hasAge()) {
//        hash = (37 * hash) + AGE_FIELD_NUMBER;
//        hash = (53 * hash) + getAge();
//      }
//      if (hasAddress()) {
//        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
//        hash = (53 * hash) + getAddress().hashCode();
//      }
//      hash = (29 * hash) + getUnknownFields().hashCode();
//      memoizedHashCode = hash;
//      return hash;
//    }
//
//    public static com.lee9213.protobuf.StudentClassName.StudentPerson parseFrom(
//        java.nio.ByteBuffer data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.lee9213.protobuf.StudentClassName.StudentPerson parseFrom(
//        java.nio.ByteBuffer data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.lee9213.protobuf.StudentClassName.StudentPerson parseFrom(
//        com.google.protobuf.ByteString data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.lee9213.protobuf.StudentClassName.StudentPerson parseFrom(
//        com.google.protobuf.ByteString data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.lee9213.protobuf.StudentClassName.StudentPerson parseFrom(byte[] data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.lee9213.protobuf.StudentClassName.StudentPerson parseFrom(
//        byte[] data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.lee9213.protobuf.StudentClassName.StudentPerson parseFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessage
//          .parseWithIOException(PARSER, input);
//    }
//    public static com.lee9213.protobuf.StudentClassName.StudentPerson parseFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessage
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//
//    public static com.lee9213.protobuf.StudentClassName.StudentPerson parseDelimitedFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessage
//          .parseDelimitedWithIOException(PARSER, input);
//    }
//
//    public static com.lee9213.protobuf.StudentClassName.StudentPerson parseDelimitedFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessage
//          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static com.lee9213.protobuf.StudentClassName.StudentPerson parseFrom(
//        com.google.protobuf.CodedInputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessage
//          .parseWithIOException(PARSER, input);
//    }
//    public static com.lee9213.protobuf.StudentClassName.StudentPerson parseFrom(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessage
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//
//    @java.lang.Override
//    public Builder newBuilderForType() { return newBuilder(); }
//    public static Builder newBuilder() {
//      return DEFAULT_INSTANCE.toBuilder();
//    }
//    public static Builder newBuilder(com.lee9213.protobuf.StudentClassName.StudentPerson prototype) {
//      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
//    }
//    @java.lang.Override
//    public Builder toBuilder() {
//      return this == DEFAULT_INSTANCE
//          ? new Builder() : new Builder().mergeFrom(this);
//    }
//
//    @java.lang.Override
//    protected Builder newBuilderForType(
//        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
//      Builder builder = new Builder(parent);
//      return builder;
//    }
//    /**
//     * Protobuf type {@code com.lee9213.proto.StudentPerson}
//     */
//    public static final class Builder extends
//        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
//        // @@protoc_insertion_point(builder_implements:com.lee9213.proto.StudentPerson)
//        com.lee9213.protobuf.StudentClassName.StudentPersonOrBuilder {
//      public static final com.google.protobuf.Descriptors.Descriptor
//          getDescriptor() {
//        return com.lee9213.protobuf.StudentClassName.internal_static_com_lee9213_protobuf_StudentPerson_descriptor;
//      }
//
//      @java.lang.Override
//      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
//          internalGetFieldAccessorTable() {
//        return com.lee9213.protobuf.StudentClassName.internal_static_com_lee9213_protobuf_StudentPerson_fieldAccessorTable
//            .ensureFieldAccessorsInitialized(
//                com.lee9213.protobuf.StudentClassName.StudentPerson.class, com.lee9213.protobuf.StudentClassName.StudentPerson.Builder.class);
//      }
//
//      // Construct using com.lee9213.protobuf.StudentClassName.StudentPerson.newBuilder()
//      private Builder() {
//
//      }
//
//      private Builder(
//          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
//        super(parent);
//
//      }
//      @java.lang.Override
//      public Builder clear() {
//        super.clear();
//        bitField0_ = 0;
//        name_ = "";
//        age_ = 0;
//        address_ = com.google.protobuf.Internal.stringDefaultValue("\346\261\237\350\213\217");
//        return this;
//      }
//
//      @java.lang.Override
//      public com.google.protobuf.Descriptors.Descriptor
//          getDescriptorForType() {
//        return com.lee9213.protobuf.StudentClassName.internal_static_com_lee9213_protobuf_StudentPerson_descriptor;
//      }
//
//      @java.lang.Override
//      public com.lee9213.protobuf.StudentClassName.StudentPerson getDefaultInstanceForType() {
//        return com.lee9213.protobuf.StudentClassName.StudentPerson.getDefaultInstance();
//      }
//
//      @java.lang.Override
//      public com.lee9213.protobuf.StudentClassName.StudentPerson build() {
//        com.lee9213.protobuf.StudentClassName.StudentPerson result = buildPartial();
//        if (!result.isInitialized()) {
//          throw newUninitializedMessageException(result);
//        }
//        return result;
//      }
//
//      @java.lang.Override
//      public com.lee9213.protobuf.StudentClassName.StudentPerson buildPartial() {
//        com.lee9213.protobuf.StudentClassName.StudentPerson result = new com.lee9213.protobuf.StudentClassName.StudentPerson(this);
//        if (bitField0_ != 0) { buildPartial0(result); }
//        onBuilt();
//        return result;
//      }
//
//      private void buildPartial0(com.lee9213.protobuf.StudentClassName.StudentPerson result) {
//        int from_bitField0_ = bitField0_;
//        int to_bitField0_ = 0;
//        if (((from_bitField0_ & 0x00000001) != 0)) {
//          result.name_ = name_;
//          to_bitField0_ |= 0x00000001;
//        }
//        if (((from_bitField0_ & 0x00000002) != 0)) {
//          result.age_ = age_;
//          to_bitField0_ |= 0x00000002;
//        }
//        if (((from_bitField0_ & 0x00000004) != 0)) {
//          result.address_ = address_;
//          to_bitField0_ |= 0x00000004;
//        }
//        result.bitField0_ |= to_bitField0_;
//      }
//
//      @java.lang.Override
//      public Builder mergeFrom(com.google.protobuf.Message other) {
//        if (other instanceof com.lee9213.protobuf.StudentClassName.StudentPerson) {
//          return mergeFrom((com.lee9213.protobuf.StudentClassName.StudentPerson)other);
//        } else {
//          super.mergeFrom(other);
//          return this;
//        }
//      }
//
//      public Builder mergeFrom(com.lee9213.protobuf.StudentClassName.StudentPerson other) {
//        if (other == com.lee9213.protobuf.StudentClassName.StudentPerson.getDefaultInstance()) return this;
//        if (other.hasName()) {
//          name_ = other.name_;
//          bitField0_ |= 0x00000001;
//          onChanged();
//        }
//        if (other.hasAge()) {
//          setAge(other.getAge());
//        }
//        if (other.hasAddress()) {
//          address_ = other.address_;
//          bitField0_ |= 0x00000004;
//          onChanged();
//        }
//        this.mergeUnknownFields(other.getUnknownFields());
//        onChanged();
//        return this;
//      }
//
//      @java.lang.Override
//      public final boolean isInitialized() {
//        return true;
//      }
//
//      @java.lang.Override
//      public Builder mergeFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws java.io.IOException {
//        if (extensionRegistry == null) {
//          throw new java.lang.NullPointerException();
//        }
//        try {
//          boolean done = false;
//          while (!done) {
//            int tag = input.readTag();
//            switch (tag) {
//              case 0:
//                done = true;
//                break;
//              case 10: {
//                name_ = input.readBytes();
//                bitField0_ |= 0x00000001;
//                break;
//              } // case 10
//              case 16: {
//                age_ = input.readInt32();
//                bitField0_ |= 0x00000002;
//                break;
//              } // case 16
//              case 26: {
//                address_ = input.readBytes();
//                bitField0_ |= 0x00000004;
//                break;
//              } // case 26
//              default: {
//                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
//                  done = true; // was an endgroup tag
//                }
//                break;
//              } // default:
//            } // switch (tag)
//          } // while (!done)
//        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//          throw e.unwrapIOException();
//        } finally {
//          onChanged();
//        } // finally
//        return this;
//      }
//      private int bitField0_;
//
//      private java.lang.Object name_ = "";
//      /**
//       * <code>optional string name = 1;</code>
//       * @return Whether the name field is set.
//       */
//      public boolean hasName() {
//        return ((bitField0_ & 0x00000001) != 0);
//      }
//      /**
//       * <code>optional string name = 1;</code>
//       * @return The name.
//       */
//      public java.lang.String getName() {
//        java.lang.Object ref = name_;
//        if (!(ref instanceof java.lang.String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          java.lang.String s = bs.toStringUtf8();
//          if (bs.isValidUtf8()) {
//            name_ = s;
//          }
//          return s;
//        } else {
//          return (java.lang.String) ref;
//        }
//      }
//      /**
//       * <code>optional string name = 1;</code>
//       * @return The bytes for name.
//       */
//      public com.google.protobuf.ByteString
//          getNameBytes() {
//        java.lang.Object ref = name_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (java.lang.String) ref);
//          name_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>optional string name = 1;</code>
//       * @param value The name to set.
//       * @return This builder for chaining.
//       */
//      public Builder setName(
//          java.lang.String value) {
//        if (value == null) { throw new NullPointerException(); }
//        name_ = value;
//        bitField0_ |= 0x00000001;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional string name = 1;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearName() {
//        name_ = getDefaultInstance().getName();
//        bitField0_ = (bitField0_ & ~0x00000001);
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional string name = 1;</code>
//       * @param value The bytes for name to set.
//       * @return This builder for chaining.
//       */
//      public Builder setNameBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) { throw new NullPointerException(); }
//        name_ = value;
//        bitField0_ |= 0x00000001;
//        onChanged();
//        return this;
//      }
//
//      private int age_ ;
//      /**
//       * <code>optional int32 age = 2;</code>
//       * @return Whether the age field is set.
//       */
//      @java.lang.Override
//      public boolean hasAge() {
//        return ((bitField0_ & 0x00000002) != 0);
//      }
//      /**
//       * <code>optional int32 age = 2;</code>
//       * @return The age.
//       */
//      @java.lang.Override
//      public int getAge() {
//        return age_;
//      }
//      /**
//       * <code>optional int32 age = 2;</code>
//       * @param value The age to set.
//       * @return This builder for chaining.
//       */
//      public Builder setAge(int value) {
//
//        age_ = value;
//        bitField0_ |= 0x00000002;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional int32 age = 2;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearAge() {
//        bitField0_ = (bitField0_ & ~0x00000002);
//        age_ = 0;
//        onChanged();
//        return this;
//      }
//
//      private java.lang.Object address_ = com.google.protobuf.Internal.stringDefaultValue("\346\261\237\350\213\217");
//      /**
//       * <code>optional string address = 3 [default = "&#92;346&#92;261&#92;237&#92;350&#92;213&#92;217"];</code>
//       * @return Whether the address field is set.
//       */
//      public boolean hasAddress() {
//        return ((bitField0_ & 0x00000004) != 0);
//      }
//      /**
//       * <code>optional string address = 3 [default = "&#92;346&#92;261&#92;237&#92;350&#92;213&#92;217"];</code>
//       * @return The address.
//       */
//      public java.lang.String getAddress() {
//        java.lang.Object ref = address_;
//        if (!(ref instanceof java.lang.String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          java.lang.String s = bs.toStringUtf8();
//          if (bs.isValidUtf8()) {
//            address_ = s;
//          }
//          return s;
//        } else {
//          return (java.lang.String) ref;
//        }
//      }
//      /**
//       * <code>optional string address = 3 [default = "&#92;346&#92;261&#92;237&#92;350&#92;213&#92;217"];</code>
//       * @return The bytes for address.
//       */
//      public com.google.protobuf.ByteString
//          getAddressBytes() {
//        java.lang.Object ref = address_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (java.lang.String) ref);
//          address_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>optional string address = 3 [default = "&#92;346&#92;261&#92;237&#92;350&#92;213&#92;217"];</code>
//       * @param value The address to set.
//       * @return This builder for chaining.
//       */
//      public Builder setAddress(
//          java.lang.String value) {
//        if (value == null) { throw new NullPointerException(); }
//        address_ = value;
//        bitField0_ |= 0x00000004;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional string address = 3 [default = "&#92;346&#92;261&#92;237&#92;350&#92;213&#92;217"];</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearAddress() {
//        address_ = getDefaultInstance().getAddress();
//        bitField0_ = (bitField0_ & ~0x00000004);
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>optional string address = 3 [default = "&#92;346&#92;261&#92;237&#92;350&#92;213&#92;217"];</code>
//       * @param value The bytes for address to set.
//       * @return This builder for chaining.
//       */
//      public Builder setAddressBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) { throw new NullPointerException(); }
//        address_ = value;
//        bitField0_ |= 0x00000004;
//        onChanged();
//        return this;
//      }
//
//      // @@protoc_insertion_point(builder_scope:com.lee9213.proto.StudentPerson)
//    }
//
//    // @@protoc_insertion_point(class_scope:com.lee9213.proto.StudentPerson)
//    private static final com.lee9213.protobuf.StudentClassName.StudentPerson DEFAULT_INSTANCE;
//    static {
//      DEFAULT_INSTANCE = new com.lee9213.protobuf.StudentClassName.StudentPerson();
//    }
//
//    public static com.lee9213.protobuf.StudentClassName.StudentPerson getDefaultInstance() {
//      return DEFAULT_INSTANCE;
//    }
//
//    private static final com.google.protobuf.Parser<StudentPerson>
//        PARSER = new com.google.protobuf.AbstractParser<StudentPerson>() {
//      @java.lang.Override
//      public StudentPerson parsePartialFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//        Builder builder = newBuilder();
//        try {
//          builder.mergeFrom(input, extensionRegistry);
//        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//          throw e.setUnfinishedMessage(builder.buildPartial());
//        } catch (com.google.protobuf.UninitializedMessageException e) {
//          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
//        } catch (java.io.IOException e) {
//          throw new com.google.protobuf.InvalidProtocolBufferException(e)
//              .setUnfinishedMessage(builder.buildPartial());
//        }
//        return builder.buildPartial();
//      }
//    };
//
//    public static com.google.protobuf.Parser<StudentPerson> parser() {
//      return PARSER;
//    }
//
//    @java.lang.Override
//    public com.google.protobuf.Parser<StudentPerson> getParserForType() {
//      return PARSER;
//    }
//
//    @java.lang.Override
//    public com.lee9213.protobuf.StudentClassName.StudentPerson getDefaultInstanceForType() {
//      return DEFAULT_INSTANCE;
//    }
//
//  }
//
//  private static final com.google.protobuf.Descriptors.Descriptor
//    internal_static_com_lee9213_protobuf_StudentPerson_descriptor;
//  private static final
//    com.google.protobuf.GeneratedMessage.FieldAccessorTable
//      internal_static_com_lee9213_protobuf_StudentPerson_fieldAccessorTable;
//
//  public static com.google.protobuf.Descriptors.FileDescriptor
//      getDescriptor() {
//    return descriptor;
//  }
//  private static  com.google.protobuf.Descriptors.FileDescriptor
//      descriptor;
//  static {
//    java.lang.String[] descriptorData = {
//      "\n\032src/protobuf/Student.proto\022\024com.lee921" +
//      "3.protobuf\"C\n\rStudentPerson\022\014\n\004name\030\001 \001(" +
//      "\t\022\013\n\003age\030\002 \001(\005\022\027\n\007address\030\003 \001(\t:\006\346\261\237\350\213\217B" +
//      "(\n\024com.lee9213.protobufB\020StudentClassNam" +
//      "e"
//    };
//    descriptor = com.google.protobuf.Descriptors.FileDescriptor
//      .internalBuildGeneratedFileFrom(descriptorData,
//        new com.google.protobuf.Descriptors.FileDescriptor[] {
//        });
//    internal_static_com_lee9213_protobuf_StudentPerson_descriptor =
//      getDescriptor().getMessageTypes().get(0);
//    internal_static_com_lee9213_protobuf_StudentPerson_fieldAccessorTable = new
//      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
//        internal_static_com_lee9213_protobuf_StudentPerson_descriptor,
//        new java.lang.String[] { "Name", "Age", "Address", });
//    descriptor.resolveAllFeaturesImmutable();
//  }
//
//  // @@protoc_insertion_point(outer_class_scope)
//}
